---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "saleor.fullname" . }}-django
  labels:
    app: {{ template "saleor.name" . }}
    chart: {{ template "saleor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "saleor.name" . }}-django
    release: {{ .Release.Name }}
